baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alice Lai"
theme = "PaperMod"

[params]
  color = "light"
  name = "Alice Lai"
  bio = "This is my bio"
  # Optional social links
  github = "yourgithubusername"

  disableSpecial1stPost = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "publications"
  name = "Publications"
  url = "/publications/"
  weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'